<script lang="ts">
  import { onMount } from 'svelte';
  import { ArrowUpRight, BarChart3, Download, Image, RefreshCw, SlidersHorizontal, Sparkles, TrendingDown, TrendingUp } from '@lucide/svelte';
  import Badge from '$lib/components/ui/Badge.svelte';
  import Button from '$lib/components/ui/Button.svelte';
  import Card from '$lib/components/ui/Card.svelte';
  import { api } from '$lib/api';
  import type { AiRecommendation, GlobalInsights } from '$lib/types';
  import { compactNumber, formatDate } from '$lib/utils';

  let data: GlobalInsights | null = null; let assetType = 'all'; let locale = 'all'; let category = 'all'; let loading = true; let error = ''; let aiLoading = false; let aiStatus = ''; let aiRecommendations: AiRecommendation[] = [];
  $: latestAi = aiRecommendations.find((item) => item.status === 'completed') ?? aiRecommendations[0] ?? null;
  $: aiPayload = latestAi?.response && typeof latestAi.response === 'object' && !Array.isArray(latestAi.response) ? latestAi.response as { summary?: string; overallAssessment?: string; recommendations?: Array<{ assetConcept?: string; format?: string; keywordCluster?: string[]; rationale?: string; confidence?: string }> } : null;
  async function load() { loading = true; error = ''; try { data = await api.getGlobalInsights({ assetType, locale, category, limit: 100 }); try { aiRecommendations = await api.getGlobalAiRecommendations(); } catch { aiRecommendations = []; } } catch (err) { error = err instanceof Error ? err.message : 'Global insights tidak dapat dimuat'; } finally { loading = false; } }
  async function generateGlobalAi() { aiLoading = true; aiStatus = ''; try { const result = await api.generateGlobalAiRecommendation({ assetType, locale, category }); aiRecommendations = [result.recommendation, ...aiRecommendations.filter((item) => item.id !== result.recommendation.id)]; aiStatus = 'Global recommendation selesai'; } catch (err) { aiStatus = err instanceof Error ? err.message : 'Global recommendation gagal'; } finally { aiLoading = false; } }
  const confidenceTone = (value: 'low' | 'medium' | 'high') => value === 'high' ? 'success' : value === 'medium' ? 'default' : 'muted';
  onMount(load);
</script>

<svelte:head><title>Global insights | StockScope</title></svelte:head>
<div class="mx-auto max-w-7xl space-y-7"><section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Cross-research intelligence</p><h1 class="mt-2 text-3xl font-bold tracking-tight">Global insights</h1><p class="mt-2 text-sm text-[#6d6a63]">Sinyal yang berulang di banyak research adalah kandidat terbaik untuk ditindaklanjuti.</p></div><div class="flex flex-wrap gap-2"><Button size="sm" on:click={generateGlobalAi} disabled={aiLoading || !data?.keywords.length}><Sparkles size={14} /> {aiLoading ? 'Generating...' : 'Generate AI readout'}</Button><a href="/discover"><Button variant="outline" size="sm">Discover ideas <ArrowUpRight size={14} /></Button></a></div></section>
  <Card className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div class="flex items-center gap-2 text-xs font-semibold text-[#77736b]"><SlidersHorizontal size={14} /> Scope</div><select aria-label="Filter asset type" bind:value={assetType} on:change={load} class="h-9 rounded-md border border-[#cfcac0] bg-[#fffdfa] px-2 text-xs text-[#3f3c37]"><option value="all">All asset types</option><option value="images">Images</option><option value="videos">Videos</option></select><select aria-label="Filter locale" bind:value={locale} on:change={load} class="h-9 rounded-md border border-[#cfcac0] bg-[#fffdfa] px-2 text-xs text-[#3f3c37]"><option value="all">All locales</option><option value="en-US">English (US)</option><option value="en-GB">English (UK)</option><option value="id-ID">Indonesian</option></select><select aria-label="Filter category" bind:value={category} on:change={load} class="h-9 rounded-md border border-[#cfcac0] bg-[#fffdfa] px-2 text-xs text-[#3f3c37]"><option value="all">All categories</option>{#each ['business','technology','wellness','sustainability','finance','lifestyle','travel','food','general'] as item}<option value={item}>{item}</option>{/each}</select><Button variant="ghost" size="icon" ariaLabel="Refresh insights" on:click={load}><RefreshCw size={15} class={loading ? 'animate-spin' : ''} /></Button><a class="sm:ml-auto" href={api.getGlobalExportUrl({ assetType, locale, category })}><Button variant="outline" size="sm"><Download size={14} /> CSV</Button></a></Card>
  {#if error}<div class="rounded-md border border-[#b94035]/25 bg-[#fff0ee] p-3 text-sm text-[#a3372f]">{error}</div>{/if}{#if loading}<Card className="p-12 text-center text-sm text-[#77736b]">Loading global insights...</Card>{:else if data}<div class="grid gap-3 sm:grid-cols-4"><Card className="p-5"><p class="text-xs font-semibold uppercase tracking-wider text-[#8d897f]">Research runs</p><p class="mt-2 text-3xl font-bold">{data.totals.researchRuns}</p></Card><Card className="p-5"><p class="text-xs font-semibold uppercase tracking-wider text-[#8d897f]">Keywords</p><p class="mt-2 text-3xl font-bold">{data.totals.keywords}</p></Card><Card className="p-5"><p class="text-xs font-semibold uppercase tracking-wider text-[#8d897f]">Assets</p><p class="mt-2 text-3xl font-bold">{data.totals.assets}</p></Card><Card className="p-5"><p class="text-xs font-semibold uppercase tracking-wider text-[#8d897f]">Snapshots</p><p class="mt-2 text-3xl font-bold">{data.totals.snapshots}</p></Card></div>
    {#if aiStatus}<div class="rounded-md border border-[#d75a3b]/20 bg-[#fff8f4] p-3 text-sm text-[#a74630]">{aiStatus}</div>{/if}{#if aiPayload}<Card className="space-y-4 border-[#eadfd8] p-5"><div><p class="eyebrow">AI readout</p><p class="mt-2 text-sm leading-6 text-[#6d6a63]">{aiPayload.summary}</p></div>{#if aiPayload.overallAssessment}<p class="rounded-md bg-[#f7f5f0] p-3 text-xs leading-5 text-[#6d6a63]">{aiPayload.overallAssessment}</p>{/if}<div class="grid gap-3 lg:grid-cols-2">{#each aiPayload.recommendations ?? [] as item}<div class="rounded-lg border border-[#e4e0d7] p-4"><div class="flex justify-between gap-2"><h3 class="text-sm font-bold">{item.assetConcept}</h3><Badge tone={item.confidence === 'high' ? 'success' : 'muted'}>{item.confidence ?? '--'}</Badge></div><p class="mt-1 text-xs text-[#a74630]">{item.format}</p><p class="mt-3 text-xs leading-5 text-[#6d6a63]">{item.rationale}</p><p class="mt-3 text-[11px] text-[#9a958b]">{(item.keywordCluster ?? []).join(', ')}</p></div>{/each}</div></Card>{/if}
    {#if data.assets.length}<Card><div class="border-b border-[#e8e3da] px-5 py-4"><p class="eyebrow">Asset evidence</p><h2 class="mt-1 text-base font-bold">Global asset ranking</h2><p class="mt-1 text-xs text-[#77736b]">Aset yang muncul berulang setelah deduplikasi snapshot.</p></div><div class="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4">{#each data.assets.slice(0, 12) as item}<a href={item.assetUrl} target="_blank" rel="noreferrer" class="group overflow-hidden rounded-lg border border-[#e4e0d7] bg-[#fffdfa]"><div class="relative aspect-[4/3] overflow-hidden bg-[#f1eee8]">{#if item.thumbnailUrl}<img src={item.thumbnailUrl} alt={item.title} loading="lazy" class="h-full w-full object-cover transition group-hover:scale-[1.03]" />{:else}<Image size={28} class="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-[#b2ada3]" />{/if}<span class="absolute right-2 top-2 rounded bg-[#242322]/85 px-2 py-1 font-mono text-xs text-white">{item.weightedScore ?? '--'}</span></div><div class="p-3"><p class="line-clamp-2 min-h-8 text-xs font-semibold text-[#3f3c37]">{item.title || 'Untitled asset'}</p><div class="mt-2 flex items-center justify-between"><Badge tone={confidenceTone(item.confidence)}>{item.confidence}</Badge><span class="text-[10px] text-[#9a958b]">{item.researchCount} research</span></div><p class="mt-2 font-mono text-[10px] text-[#9a958b]">D {item.bestDownloadRank ?? '--'} · R {item.bestRelevanceRank ?? '--'} · New {item.bestRecentRank ?? '--'}</p></div></a>{/each}</div></Card>{/if}
    {#if !data.keywords.length}<Card className="p-12 text-center"><BarChart3 size={20} class="mx-auto text-[#b2ada3]" /><p class="mt-3 text-sm font-bold">Belum ada global keyword snapshot</p><p class="mt-1 text-xs text-[#77736b]">Jalankan research Full atau Page One untuk membangun context.</p></Card>{:else}<Card><div class="border-b border-[#e8e3da] px-5 py-4"><p class="eyebrow">Keyword opportunity</p><h2 class="mt-1 text-base font-bold">Global ranking</h2></div><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left text-xs"><thead class="border-b border-[#e8e3da] text-[10px] uppercase tracking-wider text-[#9a958b]"><tr><th class="px-5 py-3">Keyword</th><th class="px-5 py-3">Score</th><th class="px-5 py-3">Confidence</th><th class="px-5 py-3">Researches</th><th class="px-5 py-3">Avg rank</th><th class="px-5 py-3">Avg results</th><th class="px-5 py-3">Trend</th><th class="px-5 py-3">Observed</th></tr></thead><tbody class="divide-y divide-[#eeeae2]">{#each data.keywords as item}<tr class="hover:bg-[#fcfaf6]"><td class="px-5 py-3"><p class="font-semibold text-[#a74630]">{item.keyword}</p><p class="mt-1 text-[10px] text-[#9a958b]">{item.assetTypes.join(', ')} · {item.categories.join(', ')}</p></td><td class="px-5 py-3"><span class="font-mono font-bold">{item.globalOpportunityScore ?? '--'}</span><div class="mt-1 h-1 w-20 rounded bg-[#efede7]"><div class="h-full rounded bg-[#d75a3b]" style={`width:${item.globalOpportunityScore ?? 0}%`}></div></div></td><td class="px-5 py-3"><Badge tone={confidenceTone(item.confidence)}>{item.confidence}</Badge></td><td class="px-5 py-3 font-mono">{item.researchCount}</td><td class="px-5 py-3 font-mono text-[#6d6a63]">{item.averageDownloadRank ?? '--'}</td><td class="px-5 py-3 font-mono text-[#6d6a63]">{item.averageResultCount === null ? '--' : compactNumber(item.averageResultCount)}</td><td class="px-5 py-3">{#if item.trend === 'up'}<span class="inline-flex items-center gap-1 text-[#39704a]"><TrendingUp size={14} /> up</span>{:else if item.trend === 'down'}<span class="inline-flex items-center gap-1 text-[#a3372f]"><TrendingDown size={14} /> down</span>{:else}<span class="text-[#9a958b]">{item.trend}</span>{/if}</td><td class="px-5 py-3 text-[10px] text-[#9a958b]">{formatDate(item.lastObservedAt)}</td></tr>{/each}</tbody></table></div></Card>{/if}
  {/if}
</div>
